__version__ = '0.2.7'
__title__ = "ShellcodeTester"
__description__ = "ShellcodeTester is a tool to assembly, compile and test ASM shellcode."
__url__ = "https://github.com/helviojunior/shellcodetester"
__build__ = 0x00
__author__ = "Helvio Junior (M4v3r1ck)"
__author_email__ = "helvio.junior@sec4us.com.br"
__license__ = "GPL-3.0"
__copyright__ = "Copyright Helvio Junior"
